spec: v1.0
desc: Catalog for working with GitHub Pages.

dataset:
  - const: src
    desc: Dir where the source templates are.
    value: $(__dir)/_$(__catalogName)
    tags: [hidden]
  
  - const: dst
    desc: Local directory where to save the files.
    value: $(workDir)
  
  - const: jekyllQ
    desc: Questions for the creation of a Jekyll website.
    tags: [hidden, questions]
    value:
      - input: websiteTitle
      - input: websiteDesc
      - input: websiteUrl
      - input: websiteBase
      - select: websiteDir
        options: ["/", "/docs"]
        defaultValue: "/docs"
      - select: jekyllTheme
        options: [jekyll-theme-minimal, minima, minimal-mistakes-jekyll]
  
defaultJobName: jekyll
jobs:
  - macro: jekyll
    title: Create a Jekyll website
    ini:
      - quiet: $answers = inquire $(jekyllQ) $(answers)
    local: [item, content]
    steps:
      - fs.createDir $(src)/$(answers.websiteDir)

      - quiet: $item = cr.getItem $(src)/_config.yaml.hbs
      - quiet: $content = hbs.render $(item,value) $(answers)
      - file.write $(content) $(dst)/_config.yaml
